version: "3.1"
services:
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./ipfsstaging:/export
      - ./ipfsdata:/data/ipfs
    command: daemon --enable-pubsub-experiment
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ethsf
      - POSTGRES_PASSWORD=ethsf
      - POSTGRES_DB=main
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
