version: "3.1"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=magna
      - POSTGRES_PASSWORD=magna
      - POSTGRES_DB=main
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
